dataset_name: "simbank"

seed: 42

encoding:
  prefix_len: 50

training:
  batch_size: 256
  max_steps: 200000
  lr: 3.0e-4
  gamma: 0.99
  target_update_every: 2000
  grad_clip_norm: 10.0

transformer:
  d_model: 128
  n_heads: 4
  n_layers: 3
  dropout: 0.1
